#!/bin/bash

LOADKEYS=/usr/bin/loadkeys
SETXKBMAP=/usr/bin/setxkbmap
LOCALECTL=/usr/bin/localectl

to_br() {
	sudo $LOADKEYS br-abnt2
	sudo $SETXKBMAP br
	sudo $LOCALECTL set-x11-keymap --no-convert br
}

to_uk() {
	sudo $LOADKEYS uk
	sudo $SETXKBMAP gb intl
	sudo $LOCALECTL set-x11-keymap --no-convert gb pc105 intl
}

current_keyboard=$(/usr/local/bin/xkb-switch)

if [ $current_keyboard == 'br' ]; then
	to_uk;
elif [ $current_keyboard == 'gb(intl)' ]; then
	to_br;
else
	echo "current unknown, switching to uk"
	to_uk;
fi
